version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: 'bookings'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
